export const firmCategories = {
  "Investment Banking": [
    "Bank of America Merrill Lynch",
    "Barclays",
    "BMO Capital Markets",
    "BNP Paribas",
    "Centerview Partners",
    "Citigroup",
    "Deutsche Bank",
    "Evercore",
    "Goldman Sachs",
    "Greenhill & Co.",
    "Guggenheim Partners",
    "Harris Williams",
    "Houlihan Lokey",
    "HSBC",
    "Jefferies",
    "J.P. Morgan",
    "Lazard",
    "Lincoln International",
    "LionTree",
    "Macquarie Capital",
    "Moelis & Company",
    "Morgan Stanley",
    "Nomura",
    "Oppenheimer & Co.",
    "Perella Weinberg Partners",
    "Piper Sandler",
    "PJT Partners",
    "Qatalyst Partners",
    "Raymond James",
    "RBC Capital Markets",
    "Robert Baird",
    "Rothschild & Co",
    "Société Générale",
    "Stifel",
    "UBS",
    "Wells Fargo Securities",
    "William Blair"
  ],
  
  "Private Equity": [
    "Advent International",
    "Apax Partners",
    "Apollo Global Management",
    "Ardian",
    "Audax Group",
    "Bain Capital",
    "Blackstone",
    "Brookfield Asset Management",
    "Cinven",
    "Clayton Dubilier & Rice",
    "CVC Capital Partners",
    "EQT",
    "Francisco Partners",
    "General Atlantic",
    "GTCR",
    "Hellman & Friedman",
    "Hg Capital",
    "H.I.G. Capital",
    "Insight Partners",
    "Intermediate Capital Group (ICG)",
    "Irving Place Capital",
    "KKR",
    "Leonard Green & Partners",
    "Marlin Equity Partners",
    "Mason Wells",
    "Monroe Capital",
    "Nordic Capital",
    "Oak Hill Capital",
    "PAI Partners",
    "Permira",
    "Platinum Equity",
    "Silver Lake",
    "Snow Phipps Group",
    "The Carlyle Group",
    "The Gores Group",
    "The Riverside Company",
    "Thoma Bravo",
    "TPG",
    "Trivest Partners",
    "TSG Consumer Partners",
    "Vista Equity Partners",
    "Warburg Pincus",
    "Welsh Carson Anderson & Stowe",
    "Wind Point Partners"
  ],
  
  "Growth Equity": [
    "Accel-KKR",
    "Battery Ventures",
    "Bregal Sagemount",
    "BuildGroup",
    "Clearlake Capital",
    "Great Hill Partners",
    "JMI Equity",
    "K1 Investment Management",
    "PSG",
    "Riverwood Capital",
    "Spectrum Equity",
    "Summit Partners",
    "TA Associates",
    "Vector Capital"
  ],
  
  "Hedge Funds": [
    "AQR Capital Management",
    "Balyasny Asset Management",
    "Brevan Howard",
    "Bridgewater Associates",
    "Citadel",
    "DE Shaw & Co",
    "Elliott Management",
    "ExodusPoint Capital Management",
    "Lone Pine Capital",
    "Man Group",
    "Marshall Wace",
    "Millennium Management",
    "Och-Ziff Capital Management",
    "Point72",
    "Renaissance Technologies",
    "Sculptor Capital Management",
    "Third Point",
    "Tiger Global Management",
    "Two Sigma",
    "Viking Global Investors"
  ],
  
  "Consulting": [
    "Accenture",
    "AlixPartners",
    "Bain & Company",
    "Booz Allen Hamilton",
    "Boston Consulting Group (BCG)",
    "Cornerstone Research",
    "Deloitte Consulting",
    "EY-Parthenon / EY Consulting",
    "FTI Consulting",
    "Huron Consulting",
    "Kearney (formerly A.T. Kearney)",
    "KPMG Advisory",
    "L.E.K. Consulting",
    "McKinsey & Company",
    "Oliver Wyman",
    "PA Consulting",
    "PwC Advisory / Strategy&",
    "Roland Berger",
    "Simon-Kucher & Partners"
  ],
  
  "Tech (FAANG+)": [
    "Adobe",
    "Airbnb",
    "Amazon",
    "Apple",
    "Google (Alphabet)",
    "Meta (Facebook)",
    "Microsoft",
    "Netflix",
    "NVIDIA",
    "Oracle",
    "Palantir",
    "Salesforce",
    "SpaceX",
    "Stripe",
    "Tesla",
    "Uber"
  ],
  
  "Venture Capital": [
    "Accel",
    "Andreessen Horowitz",
    "Battery Ventures",
    "Benchmark",
    "Bessemer Venture Partners",
    "Founders Fund",
    "General Catalyst",
    "Greylock Partners",
    "Index Ventures",
    "Insight Partners",
    "Kleiner Perkins",
    "Lightspeed Venture Partners",
    "NEA (New Enterprise Associates)",
    "Sequoia Capital",
    "Tiger Global"
  ],

  "Other": [
    "Other"
  ]
}

// Flatten all firms into a single sorted array for easy searching
export const allFirms = Object.values(firmCategories)
  .flat()
  .sort((a, b) => a.localeCompare(b))

// Get all unique firm types
export const firmTypes = Object.keys(firmCategories)
